name: Rob么 Curador de Wallpapers

on:
  schedule:
    - cron: '0 */6 * * *' # Roda a cada 6 horas
  workflow_dispatch: # Permite rodar manualmente clicando num bot茫o

permissions:
  contents: write

jobs:
  baixar-e-atualizar:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar reposit贸rio (Checkout)
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar bibliotecas
      run: |
        pip install requests

    - name: Rodar o Rob么
      run: python bot_wallpapers.py

    - name: Salvar e Enviar mudan莽as (Commit & Push)
      run: |
        git config --global user.name "Rob么 GitHub"
        git config --global user.email "robo@github.com"
        git add .
        git commit -m " Nova imagem adicionada via Automa莽茫o" || echo "Nada para commitar"
        git push